name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    env:
      CONFIGURATION: Release
      RUNTIME: win-x64
      DOTNET_VERSION: '8.0.x'

    steps:
    - name: Publish self-contained build
      run: dotnet publish -c ${{ env.CONFIGURATION }} -r ${{ env.RUNTIME }} --self-contained true --output ./build/publish

    - name: Copy extras
      run: |
        cp README.md build/publish/
        cp LICENSE build/publish/

    - name: Zip published files
      working-directory: ./build/publish
      run: |
        powershell Compress-Archive -Path * -DestinationPath ../../Oggify-${{ github.ref_name }}.zip